apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: broker
  selector:
    app: kafka
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-bootstrap
  namespace: kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: broker
  selector:
    app: kafka
  type: ClusterIP
