apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
type: Opaque
stringData:
  root-user: minioadmin     # Tài khoản mặc định
  root-password: minioadmin # Mật khẩu mặc định
